theme: jekyll-theme-hacker
title:
  en: Low-Resource Language Processing Evaluation
  ru: Оценка методов обработки малоресурсных языков
contact_group:  https://groups.google.com/g/lowresource-eval-2021
index:
  en: enindex.html
  ru: index.html
markdown: kramdown
kramdown:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data